addSbtPlugin("org.scalameta"     % "sbt-scalafmt"               % "2.3.2")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"             % "1.5.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"                 % "5.3.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-ghpages"                % "0.6.2")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"                 % "0.4.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"                   % "1.4.0")
addSbtPlugin("io.github.jonas"   % "sbt-paradox-material-theme" % "0.6.0")
