name: CI
  on:
    push:
#      branches: master
  jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          scala: [2.12.10, 2.13.1]
      steps:
        - uses: actions/checkout@v1
        - uses: olafurpg/setup-scala@v5
        - name: Format Check
          if: matrix.scala == '2.13.1'
          run: sbt ++${{matrix.scala}} fmtCheck
        - name: test
          run: sbt ++${{matrix.scala}} test