name: CI
on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12.12, 2.13.3]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.8
      - name: Format Check
        if: matrix.scala == '2.13.3'
        run: sbt ++${{matrix.scala}} fmtCheck
      - name: test
        run: sbt ++${{matrix.scala}} test