name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12.10, 2.13.1]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Release ${{ github.ref }}
        run:  sbt ++${{matrix.scala}} ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
